# Generated by Django 3.0.2 on 2020-02-03 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=5)),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Book_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarymanager.Book')),
                ('subscribed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
